# Generated by Django 4.0.6 on 2022-08-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='africa',
            name='capital',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='africa',
            name='country',
            field=models.CharField(max_length=30),
        ),
    ]
